# Force update to trigger GitHub Actions detection

name: Run Coin Radar Automation

on:
  schedule:
    - cron: "0 */4 * * *"  # Runs every 4 hours (adjust as needed)
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Ensure it's the correct version

      - name: Install Dependencies
        run: |
          pip install selenium schedule  # Installs required packages

      - name: Run Coin Radar Script
        run: python coin_radar.py
