name: Coin Radar Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debugging: Print directory structure to verify
      - name: Debug Directory Structure
        run: |
          pwd
          ls -R

      # Run the Coin Radar script in the 'src' folder
      - name: Run Coin Radar Script
        run: python src/coin_radar.py
