name: Run Coin Radar Automation

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"  # every 8 hours

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 1) Install Google Chrome
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 2) Download & Install Matching ChromeDriver
      - name: Install ChromeDriver
        run: |
          # Extract the major version of Google Chrome (e.g. 134)
          CHROME_VERSION=$(google-chrome --version | grep -Po '(?<=Google Chrome )\d+')
          # Get matching ChromeDriver version from storage.googleapis.com
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          echo "Chrome major version: $CHROME_VERSION"
          echo "ChromeDriver matching version: $CHROMEDRIVER_VERSION"

          # Download and install ChromeDriver
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Install Dependencies
        run: |
          pip install selenium schedule requests openai

      - name: Run Coin Radar Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python coin_radar.py
