name: Coin Radar Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Directory Structure
        run: |
          pwd
          ls -R

      - name: Run Coin Radar Script with Logging
        run: python src/coin_radar.py
        continue-on-error: true  # Allow the job to continue even if an error occurs
