name: Run Coin Radar Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"  # every 8 hours

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      # Create a symlink so "/usr/bin/google-chrome" points to Chromium
      - name: Symlink Chromium to google-chrome
        run: sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome

      - name: Install Dependencies
        run: |
          pip install selenium schedule requests openai

      - name: Run Coin Radar Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python coin_radar.py
