name: Coin Radar Automation

on:
  push:
    branches:
      - main  # Or the branch you're working on
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug: Print directory structure for verification
      - name: Debug Directory
        run: |
          pwd
          ls -R

      # Run the Python script from the "src" folder
      - name: Run Coin Radar Script
        run: python src/coin_radar.py

