name: Coin Radar Automation

on:
  schedule:
    - cron: "15 0,4,8,12,16,20 * * *"  # Runs at 00:15, 04:15, 08:15, etc.
    - cron: "45 0,4,8,12,16,20 * * *"  # Runs 30 minutes after the first run

  push:
    branches:
      - main  # Triggers on push to the main branch
  workflow_dispatch:  # Allows manual trigger via GitHub Actions tab

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug: Print directory structure to verify
      - name: Debug Directory Structure
        run: |
          pwd
          ls -R

      # Step 3: Run the Coin Radar script
      - name: Run Coin Radar Script
        run: python src/coin_radar.py
